//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanB.Butler.Bot.Dictionary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dialogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dialogs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlanB.Butler.Bot.Dictionary.Dialogs", typeof(Dialogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesen Monat beträgt ihre Belastung: {0} €.
        /// </summary>
        public static string CreditDialog_MonthDepts {
            get {
                return ResourceManager.GetString("CreditDialog_MonthDepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es liegt für diesen Monat noch keine Rechnung vor. Soll ich für letzten Monat nachschauen?.
        /// </summary>
        public static string CreditDialog_NoBill {
            get {
                return ResourceManager.GetString("CreditDialog_NoBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es liegt für den letzten Monat ebenfalls keine Rechnung vor. Leider kann ich Ihnen nicht weiterhelfen..
        /// </summary>
        public static string CreditDialog_NoBillLastMonth {
            get {
                return ResourceManager.GetString("CreditDialog_NoBillLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben diesen Monat noch nichts bestellt. Soll ich für letzten Monat nachschauen..
        /// </summary>
        public static string CreditDialog_NoOrder {
            get {
                return ResourceManager.GetString("CreditDialog_NoOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heute beträgt die Belastung: {0} €.
        /// </summary>
        public static string DailyCreditDialog_Depts {
            get {
                return ResourceManager.GetString("DailyCreditDialog_Depts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für den Kunden wurde: {0} berechnet..
        /// </summary>
        public static string DailyCreditDialog_OrderCostumer {
            get {
                return ResourceManager.GetString("DailyCreditDialog_OrderCostumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben heute {0} bestellt und dies bei dem Restaurant {1}..
        /// </summary>
        public static string DailyCreditDialog_OrderedAt {
            get {
                return ResourceManager.GetString("DailyCreditDialog_OrderedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für Sie wurde: {0} berechnet..
        /// </summary>
        public static string DailyCreditDialog_OrderMe {
            get {
                return ResourceManager.GetString("DailyCreditDialog_OrderMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für den Prakikanten wurde: {0} berechnet..
        /// </summary>
        public static string DailyCreditDialog_OrderTrainee {
            get {
                return ResourceManager.GetString("DailyCreditDialog_OrderTrainee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insgesamt werden für den Kunden {0} berechnet..
        /// </summary>
        public static string DailyCreditDialog_SumCostumer {
            get {
                return ResourceManager.GetString("DailyCreditDialog_SumCostumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insgesamt werden Ihnen {0} berechnet..
        /// </summary>
        public static string DailyCreditDialog_SumMe {
            get {
                return ResourceManager.GetString("DailyCreditDialog_SumMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insgesamt werden für den Prakitkanten {0} berechnet..
        /// </summary>
        public static string DailyCreditDialog_SumTrainee {
            get {
                return ResourceManager.GetString("DailyCreditDialog_SumTrainee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll {0} gelöscht werden?.
        /// </summary>
        public static string DeletDialog_DeletePrompt {
            get {
                return ResourceManager.GetString("DeletDialog_DeletePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Bestellung wurde entfernt..
        /// </summary>
        public static string DeletDialog_DeleteSucess {
            get {
                return ResourceManager.GetString("DeletDialog_DeleteSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An diesem Tag liegt keine Bestellung vor..
        /// </summary>
        public static string DeletDialog_NoOrder {
            get {
                return ResourceManager.GetString("DeletDialog_NoOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für welchen Tag möchten Sie ihre Bestellung löschen?.
        /// </summary>
        public static string DeletDialog_TimePrompt {
            get {
                return ResourceManager.GetString("DeletDialog_TimePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für wen möchten Sie die Bestellung löschen?.
        /// </summary>
        public static string DeletDialog_WhoPrompt {
            get {
                return ResourceManager.GetString("DeletDialog_WhoPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo, Ich bin dein persönlicher Essensbestell Bot. Zu den schon angezeigten Befehlen kann ich noch.
        /// </summary>
        public static string InterruptDialog_HelpText {
            get {
                return ResourceManager.GetString("InterruptDialog_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie viele Essen möchten Sie bestellen?.
        /// </summary>
        public static string NextOrderDialog_AmountFoodPrompt {
            get {
                return ResourceManager.GetString("NextOrderDialog_AmountFoodPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für welche Firma soll Essen bestellt werden? Bitte geben Sie zusätzlich den Namen des Kunden/der Kunden an..
        /// </summary>
        public static string NextOrderDialog_CompanyPrompt {
            get {
                return ResourceManager.GetString("NextOrderDialog_CompanyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde.
        /// </summary>
        public static string NextOrderDialog_Costumer {
            get {
                return ResourceManager.GetString("NextOrderDialog_Costumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da ist wohl etwas schiefgegangen. Bitte beginnen Sie nochmal von vorn ..
        /// </summary>
        public static string NextOrderDialog_Error {
            get {
                return ResourceManager.GetString("NextOrderDialog_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei deiner Bestellung ist etwas schiefgegangen. Bitte bestellen Sie noch einmal..
        /// </summary>
        public static string NextOrderDialog_Error1 {
            get {
                return ResourceManager.GetString("NextOrderDialog_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welches Essen möchten Sie bestellen?.
        /// </summary>
        public static string NextOrderDialog_FoodPrompt {
            get {
                return ResourceManager.GetString("NextOrderDialog_FoodPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für mich.
        /// </summary>
        public static string NextOrderDialog_Myself {
            get {
                return ResourceManager.GetString("NextOrderDialog_Myself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie ist der Namen des Praktikanten/ der Praktikatin?.
        /// </summary>
        public static string NextOrderDialog_NameTraineePrompt {
            get {
                return ResourceManager.GetString("NextOrderDialog_NameTraineePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei welchem Restauarant möchten Sie bestellen?.
        /// </summary>
        public static string NextOrderDialog_RestaurantPrompt {
            get {
                return ResourceManager.GetString("NextOrderDialog_RestaurantPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Bestellung wurde gespeichert..
        /// </summary>
        public static string NextOrderDialog_SaveOrder {
            get {
                return ResourceManager.GetString("NextOrderDialog_SaveOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praktikant.
        /// </summary>
        public static string NextOrderDialog_Trainee {
            get {
                return ResourceManager.GetString("NextOrderDialog_Trainee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für wen möchten Sie bestellen?.
        /// </summary>
        public static string NextOrderDialog_WhoPrompt {
            get {
                return ResourceManager.GetString("NextOrderDialog_WhoPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fehler.
        /// </summary>
        public static string OtherDayDialog_Error {
            get {
                return ResourceManager.GetString("OtherDayDialog_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es tut mir Leid. Es ist ein Fehler unterlaufen. Bitt versuchen sie es erneut..
        /// </summary>
        public static string OtherDayDialog_Error1 {
            get {
                return ResourceManager.GetString("OtherDayDialog_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tut mir Leid. Ich konnte Sie nicht verstehen. Bitte benutzen Sie Befehle, welche mir bekannt sind..
        /// </summary>
        public static string OtherDayDialog_Error2 {
            get {
                return ResourceManager.GetString("OtherDayDialog_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie ihren Namen ein..
        /// </summary>
        public static string OtherDayDialog_NamePrompt {
            get {
                return ResourceManager.GetString("OtherDayDialog_NamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essen wird bei {0} bestellt..
        /// </summary>
        public static string OtherDayDialog_Order {
            get {
                return ResourceManager.GetString("OtherDayDialog_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danke.
        /// </summary>
        public static string OtherDayDialog_Thanks {
            get {
                return ResourceManager.GetString("OtherDayDialog_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für welchen Tag möchten Sie Essen bestellen?.
        /// </summary>
        public static string OtherDayDialog_TimePrompt {
            get {
                return ResourceManager.GetString("OtherDayDialog_TimePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagesbestellung.
        /// </summary>
        public static string OverviewDialog_DaysOrder {
            get {
                return ResourceManager.GetString("OverviewDialog_DaysOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellung entfernen.
        /// </summary>
        public static string OverviewDialog_DeleteOrder {
            get {
                return ResourceManager.GetString("OverviewDialog_DeleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle Sie eines der unten stehenden Ereignissen aus oder schreibe Sie &quot;Hilfe&quot; um zu erfahren was ich sonst noch alles kann..
        /// </summary>
        public static string OverviewDialog_Help {
            get {
                return ResourceManager.GetString("OverviewDialog_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essen bestellen.
        /// </summary>
        public static string OverviewDialog_OrderFood {
            get {
                return ResourceManager.GetString("OverviewDialog_OrderFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für einen anderen Tag bestellen.
        /// </summary>
        public static string OverviewDialog_OtherDay {
            get {
                return ResourceManager.GetString("OverviewDialog_OtherDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monatliche Belastung anzeigen.
        /// </summary>
        public static string OverviewDialog_ShowDepts {
            get {
                return ResourceManager.GetString("OverviewDialog_ShowDepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was möchten Sie tun?.
        /// </summary>
        public static string OverviewDialog_WhatNow {
            get {
                return ResourceManager.GetString("OverviewDialog_WhatNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay, hier ist der Essensplan von {0}.
        /// </summary>
        public static string PlanDialog_MenuCard {
            get {
                return ResourceManager.GetString("PlanDialog_MenuCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von welchem Restaurant möchten Sie die Speisekarte sehen?.
        /// </summary>
        public static string PlanDialog_MenuCardPrompt {
            get {
                return ResourceManager.GetString("PlanDialog_MenuCardPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für {0} ist leider keine Speisekarte vorhanden..
        /// </summary>
        public static string PlanDialog_NoMenuCard {
            get {
                return ResourceManager.GetString("PlanDialog_NoMenuCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie die Speisekarte eines anderen Restaurant anschauen?.
        /// </summary>
        public static string PlanDialog_OtherMenuCard {
            get {
                return ResourceManager.GetString("PlanDialog_OtherMenuCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Ein weiteres essen für z.B. Praktikanten oder Kunden bestellen. Daür bitte &apos;Weiteres Essen bestellen&apos; eingeben..
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Ein Essen für einen anderen Tag in dieser Woche bestellen. Dafür bitte &apos;für einen anderen Tag Essen bestellen eingeben..
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Zur Kontrolle kann man mich fragen was man heute bestellt hat. Dafür bitte &apos;Was habe ich heute bestellt&apos; eingeben..
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guten Tag, ich bin der PlanButler, ihr Essensorganisator. Wie kann ich ihnen helfen? Tippen Sie eine Taste um fortzufahren..
        /// </summary>
        public static string TeamBots_WelcomeMessage {
            get {
                return ResourceManager.GetString("TeamBots_WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
