//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanB.Butler.Library.Test.Dictionary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlanB.Butler.Library.Test.Dictionary.main", typeof(main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insgesamt werden für den Kunden .
        /// </summary>
        public static string allCostumer {
            get {
                return ResourceManager.GetString("allCostumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insgesamt werden Ihnen .
        /// </summary>
        public static string allMe {
            get {
                return ResourceManager.GetString("allMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insgesamt werden für den Prakitkanten .
        /// </summary>
        public static string allTrainee {
            get {
                return ResourceManager.GetString("allTrainee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie viele Essen möchten Sie bestellen?.
        /// </summary>
        public static string amountFood {
            get {
                return ResourceManager.GetString("amountFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bei.
        /// </summary>
        public static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to berechnet.
        /// </summary>
        public static string calculated {
            get {
                return ResourceManager.GetString("calculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für welche Firma soll Essen bestellt werden? Bitte geben Sie zusätzlich den Namen des Kunden/der Kunden an..
        /// </summary>
        public static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde.
        /// </summary>
        public static string costumer {
            get {
                return ResourceManager.GetString("costumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagesbestellung.
        /// </summary>
        public static string daysOrder {
            get {
                return ResourceManager.GetString("daysOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll .
        /// </summary>
        public static string delete1 {
            get {
                return ResourceManager.GetString("delete1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gelöscht werden?.
        /// </summary>
        public static string delete2 {
            get {
                return ResourceManager.GetString("delete2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Bestellung wurde entfernt..
        /// </summary>
        public static string deleteSuccess {
            get {
                return ResourceManager.GetString("deleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da ist wohl etwas schiefgegangen. Bitte beginnen Sie nochmal von vorn ..
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei deiner Bestellung ist etwas schiefgegangen. Bitte bestellen Sie noch einmal..
        /// </summary>
        public static string error2 {
            get {
                return ResourceManager.GetString("error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es tut mir Leid, es muss ein Fehler unterlaufen sein. Bitte versuchen Sie es noch einmal..
        /// </summary>
        public static string errorOtherDay {
            get {
                return ResourceManager.GetString("errorOtherDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tut mir Leid. Ich konnte Sie nicht verstehen. Bitte benutzen Sie Befehle, welche mir bekannt sind..
        /// </summary>
        public static string errorOtherDay2 {
            get {
                return ResourceManager.GetString("errorOtherDay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to €.
        /// </summary>
        public static string euro {
            get {
                return ResourceManager.GetString("euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extern.
        /// </summary>
        public static string external {
            get {
                return ResourceManager.GetString("external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welches Essen möchten Sie bestellen?.
        /// </summary>
        public static string food {
            get {
                return ResourceManager.GetString("food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freitag.
        /// </summary>
        public static string friday {
            get {
                return ResourceManager.GetString("friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle Sie eines der unten stehenden Ereignissen aus oder schreibe &quot;Hilfe&quot; um zu erfahren was ich sonst noch alles kann..
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intern.
        /// </summary>
        public static string internally {
            get {
                return ResourceManager.GetString("internally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intership.
        /// </summary>
        public static string intership {
            get {
                return ResourceManager.GetString("intership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzten Monat betrug ihre Belastung:.
        /// </summary>
        public static string lastMonthBruden {
            get {
                return ResourceManager.GetString("lastMonthBruden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für mich.
        /// </summary>
        public static string me {
            get {
                return ResourceManager.GetString("me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montag.
        /// </summary>
        public static string monday {
            get {
                return ResourceManager.GetString("monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesen Monat liegt ihre Belastung bei: .
        /// </summary>
        public static string monthBurden {
            get {
                return ResourceManager.GetString("monthBurden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie ihren Namen ein..
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie ist der Namen des Praktikanten?.
        /// </summary>
        public static string nameTrainee {
            get {
                return ResourceManager.GetString("nameTrainee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es liegt für diesen Monat noch keine Rechnung vor. Soll ich für letzten Monat nachschauen?.
        /// </summary>
        public static string noBillMonth {
            get {
                return ResourceManager.GetString("noBillMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es liegt für den letzten Monat ebenfalls keine Rechnung vor. Leider kann ich Ihnen nicht weiterhelfen..
        /// </summary>
        public static string noBillToday {
            get {
                return ResourceManager.GetString("noBillToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben diesen Monat noch nichts bestellt. Soll ich für letzten Monat nachschauen..
        /// </summary>
        public static string noOrderMonth {
            get {
                return ResourceManager.GetString("noOrderMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An diesem Tag liegt keine Bestellung vor..
        /// </summary>
        public static string noOrderToday {
            get {
                return ResourceManager.GetString("noOrderToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie möchten bei.
        /// </summary>
        public static string order1 {
            get {
                return ResourceManager.GetString("order1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bestellen..
        /// </summary>
        public static string order2 {
            get {
                return ResourceManager.GetString("order2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bestellt.
        /// </summary>
        public static string ordered {
            get {
                return ResourceManager.GetString("ordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für den Externen wurde:.
        /// </summary>
        public static string orderExternal {
            get {
                return ResourceManager.GetString("orderExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essen bestellen.
        /// </summary>
        public static string orderFood {
            get {
                return ResourceManager.GetString("orderFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für Sie wurde:.
        /// </summary>
        public static string orderMe {
            get {
                return ResourceManager.GetString("orderMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für den Prakikanten wurde:.
        /// </summary>
        public static string orderTrainee {
            get {
                return ResourceManager.GetString("orderTrainee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für welchen Tag möchten Sie Essen bestellen?.
        /// </summary>
        public static string orderWhen {
            get {
                return ResourceManager.GetString("orderWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für welchen Tag möchten Sie ihre Bestellung löschen?.
        /// </summary>
        public static string queryDayDelete {
            get {
                return ResourceManager.GetString("queryDayDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für wen möchten Sie bestellen?.
        /// </summary>
        public static string queryOrder {
            get {
                return ResourceManager.GetString("queryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellung entfernen.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danke! Bei welchem Restauarant möchten Sie bestellen?.
        /// </summary>
        public static string restaurant {
            get {
                return ResourceManager.GetString("restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samstag.
        /// </summary>
        public static string saturday {
            get {
                return ResourceManager.GetString("saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Bestellung wurde gespeichert..
        /// </summary>
        public static string saveOrder {
            get {
                return ResourceManager.GetString("saveOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montaliche Belastung anzeigen.
        /// </summary>
        public static string showMonthBruden {
            get {
                return ResourceManager.GetString("showMonthBruden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonntag.
        /// </summary>
        public static string sunday {
            get {
                return ResourceManager.GetString("sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danke.
        /// </summary>
        public static string thanks {
            get {
                return ResourceManager.GetString("thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donnerstag.
        /// </summary>
        public static string thursday {
            get {
                return ResourceManager.GetString("thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heute beträgt die Belastung:.
        /// </summary>
        public static string todayBurden {
            get {
                return ResourceManager.GetString("todayBurden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heute wird bei dem Restaurant .
        /// </summary>
        public static string todayRestaurant {
            get {
                return ResourceManager.GetString("todayRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praktikant.
        /// </summary>
        public static string trainee {
            get {
                return ResourceManager.GetString("trainee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dienstag.
        /// </summary>
        public static string tuesday {
            get {
                return ResourceManager.GetString("tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mittwoch.
        /// </summary>
        public static string wednesday {
            get {
                return ResourceManager.GetString("wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was möchten Sie tun?.
        /// </summary>
        public static string whatNow {
            get {
                return ResourceManager.GetString("whatNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tut mir Leid. Ich habe Sie nicht verstanden. Bitte benutzen Sie Befehle, welche mir bekannt sind..
        /// </summary>
        public static string wrongInput {
            get {
                return ResourceManager.GetString("wrongInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben heute .
        /// </summary>
        public static string youOrderedToday {
            get {
                return ResourceManager.GetString("youOrderedToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to und bei dem Restaurant..
        /// </summary>
        public static string youOrderedToday2 {
            get {
                return ResourceManager.GetString("youOrderedToday2", resourceCulture);
            }
        }
    }
}
