name: .NET Core - PlanB.Butler.Bot

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build PlanB.Butler.Bot.sln --configuration Release

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Test with dotnet
      run: dotnet test PlanB.Butler.Bot/PlanB.Butler.Bot.Test/PlanB.Butler.Bot.Test.csproj --configuration Release --collect:"Code Coverage"

 
